### ISSUE TITLE
AR for static libraries?

### ISSUE THREAD

**Issue by denzp** [indutny/pyg#4]
The build fails with

```
[10/13] LIBTOOL-STATIC build/0/parson/parson.a
FAILED: libtool -static -o build/0/parson/parson.a build/0/parson/parson_0.o
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
ninja: build stopped: subcommand failed.
```

my ubuntu doesn't provide libtool by default so I have installed it from apt-get. The version is `libtool (GNU libtool) 2.4.2`

but the next rule works fine for me:

```
rule ar_parson_0
  command = ar rsc $out $in
  description = AR $out
```

**Comment by denzp** [comment]
ninja to build itself also using `ar`. http://martine.github.io/ninja/build.ninja.html

**Comment by indutny** [comment]
Thanks, fixed!
